replicaCount: 1
fullnameOverride: dispatch
image:
  repository: sumanthb9908/sumstore-dispatch
  tag: 528482677190856017504ac93960f5980564c2d0
  pullPolicy: IfNotPresent
containerPort:
  enabled: false
service:
  enabled: false
config:
  AMQP_HOST: rabbitmq
  DISPATCH_ERROR_PERCENT: "0"
existingSecret: dispatch-rabbitmq-secret
probes:
  startup:
    enabled: false
  readiness:
    enabled: false
  liveness:
    enabled: false
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
