replicaCount: 1
fullnameOverride: ratings
image:
  repository: sumanthb9908/sumstore-ratings
  tag: bfb3d255b679578a88bb45c1975628bc98218dca
  pullPolicy: IfNotPresent
containerPort:
  enabled: true
  port: 8080
service:
  enabled: true
  type: ClusterIP
  port: 8080
  targetPort: 8080
config:
  APP_ENV: prod
  CATALOGUE_URL: http://catalogue:8080
  PDO_URL: "mysql:host=mysql;dbname=ratings;charset=utf8mb4"
existingSecret: ratings-db-secret
probes:
  startup:
    enabled: true
    path: /_health
    initialDelaySeconds: 0
    periodSeconds: 2
    failureThreshold: 20
  readiness:
    enabled: true
    path: /_health
    initialDelaySeconds: 5
    periodSeconds: 10
  liveness:
    enabled: false
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
