apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sumstore
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sumanthbcloud/Sumstore-GitOps.git
    targetRevision: main
    path: helm/sumstore
    helm:
      valueFiles:
        - values/cart.yaml
        - values/catalogue.yaml
        - values/dispatch.yaml
        - values/payment.yaml
        - values/ratings.yaml
        - values/shipping.yaml
        - values/user.yaml
        - values/web.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: sumstore
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
