{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-service.fullname" . }}
  labels:
    {{- include "app-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default 8080 }}
      targetPort: {{ .Values.service.targetPort | default 8080 }}
      protocol: TCP
      name: http
  selector:
    {{- include "app-service.selectorLabels" . | nindent 4 }}
{{- end }}
