web:
  replicaCount: 1
  fullnameOverride: web
  image:
    repository: sumanthb9908/sumstore-web
    tag: 4853a503c2484a72300214e182e18ad4586a40be
    pullPolicy: IfNotPresent
  containerPort:
    enabled: true
    port: 8080
  service:
    enabled: true
    type: ClusterIP
    port: 8080
    targetPort: 8080
  config:
    CATALOGUE_HOST: catalogue
    USER_HOST: user
    CART_HOST: cart
    SHIPPING_HOST: shipping
    PAYMENT_HOST: payment
    RATINGS_HOST: ratings
  probes:
    startup:
      enabled: false
    readiness:
      enabled: true
      path: /
      initialDelaySeconds: 5
      periodSeconds: 10
    liveness:
      enabled: true
      path: /
      initialDelaySeconds: 10
      periodSeconds: 10
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 128Mi
